export const ROOM_POPULATE = 'FACILITY_ROOM_POPULATE';
export const ROOM_ON_POPULATE = 'FACILITY_ROOM_ON_POPULATE';
export const DEVICES_POPULATE = 'FACILITY_DEVICES_POPULATE';
export const DEVICES_ON_POPULATE = 'FACILITY_DEVICES_ON_POPULATE';
